/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { VisitorService } from "../visitor.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { VisitorCreateInput } from "./VisitorCreateInput";
import { Visitor } from "./Visitor";
import { VisitorFindManyArgs } from "./VisitorFindManyArgs";
import { VisitorWhereUniqueInput } from "./VisitorWhereUniqueInput";
import { VisitorUpdateInput } from "./VisitorUpdateInput";
import { ChatRoomFindManyArgs } from "../../chatRoom/base/ChatRoomFindManyArgs";
import { ChatRoom } from "../../chatRoom/base/ChatRoom";
import { ChatRoomWhereUniqueInput } from "../../chatRoom/base/ChatRoomWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class VisitorControllerBase {
  constructor(
    protected readonly service: VisitorService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Visitor })
  @nestAccessControl.UseRoles({
    resource: "Visitor",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createVisitor(
    @common.Body() data: VisitorCreateInput
  ): Promise<Visitor> {
    return await this.service.createVisitor({
      data: data,
      select: {
        createdAt: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Visitor] })
  @ApiNestedQuery(VisitorFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Visitor",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async visitors(@common.Req() request: Request): Promise<Visitor[]> {
    const args = plainToClass(VisitorFindManyArgs, request.query);
    return this.service.visitors({
      ...args,
      select: {
        createdAt: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Visitor })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Visitor",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async visitor(
    @common.Param() params: VisitorWhereUniqueInput
  ): Promise<Visitor | null> {
    const result = await this.service.visitor({
      where: params,
      select: {
        createdAt: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Visitor })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Visitor",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateVisitor(
    @common.Param() params: VisitorWhereUniqueInput,
    @common.Body() data: VisitorUpdateInput
  ): Promise<Visitor | null> {
    try {
      return await this.service.updateVisitor({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Visitor })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Visitor",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteVisitor(
    @common.Param() params: VisitorWhereUniqueInput
  ): Promise<Visitor | null> {
    try {
      return await this.service.deleteVisitor({
        where: params,
        select: {
          createdAt: true,
          id: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/chatRooms")
  @ApiNestedQuery(ChatRoomFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "ChatRoom",
    action: "read",
    possession: "any",
  })
  async findChatRooms(
    @common.Req() request: Request,
    @common.Param() params: VisitorWhereUniqueInput
  ): Promise<ChatRoom[]> {
    const query = plainToClass(ChatRoomFindManyArgs, request.query);
    const results = await this.service.findChatRooms(params.id, {
      ...query,
      select: {
        admin: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        updatedAt: true,

        visitor: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/chatRooms")
  @nestAccessControl.UseRoles({
    resource: "Visitor",
    action: "update",
    possession: "any",
  })
  async connectChatRooms(
    @common.Param() params: VisitorWhereUniqueInput,
    @common.Body() body: ChatRoomWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      chatRooms: {
        connect: body,
      },
    };
    await this.service.updateVisitor({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/chatRooms")
  @nestAccessControl.UseRoles({
    resource: "Visitor",
    action: "update",
    possession: "any",
  })
  async updateChatRooms(
    @common.Param() params: VisitorWhereUniqueInput,
    @common.Body() body: ChatRoomWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      chatRooms: {
        set: body,
      },
    };
    await this.service.updateVisitor({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/chatRooms")
  @nestAccessControl.UseRoles({
    resource: "Visitor",
    action: "update",
    possession: "any",
  })
  async disconnectChatRooms(
    @common.Param() params: VisitorWhereUniqueInput,
    @common.Body() body: ChatRoomWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      chatRooms: {
        disconnect: body,
      },
    };
    await this.service.updateVisitor({
      where: params,
      data,
      select: { id: true },
    });
  }
}
